---
# tasks file for ufw
- name: Show facts available on the system
  ansible.builtin.debug:
    var: group_hosts

- name: Reset old rules
  community.general.ufw:
    state: reset
  when: reset_old_rules | bool

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: 'on'

- name: Open public ports
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.protocol }}"
    comment: "{{ item.description }}"
  loop: "{{ public_ports }}"

- name: Allow all access from networks to this host
  community.general.ufw:
    rule: allow
    src: '{{ item.net }}'
    comment: "{{ item.description }}"
  loop: "{{ allow_networks }}"

- name: Allow all access from group hosts
  community.general.ufw:
    rule: allow
    src: '{{ item }}'
    comment: "Ansible group hosts access"
  loop: "{{ allow_group_hosts }}"
  when: allow_group_hosts is defined

- name: Default policy for incoming traffic
  community.general.ufw:
    direction: incoming
    default: deny

- name: Default policy for outgoing traffic
  community.general.ufw:
    direction: outgoing
    default: allow
...
